create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  path text,
  referrer text,
  language text,
  viewport text,
  user_agent text,
  created_at timestamptz not null default now()
);

alter table public.analytics_events enable row level security;

drop policy if exists "analytics_events_admin_only" on public.analytics_events;
create policy "analytics_events_admin_only"
on public.analytics_events
for all
using (false)
with check (false);

create index if not exists analytics_events_created_at_idx
on public.analytics_events (created_at desc);

create index if not exists analytics_events_type_idx
on public.analytics_events (event_type);
