alter table public.teams
  add column if not exists external_id text,
  add column if not exists provider text,
  add column if not exists region text,
  add column if not exists updated_at timestamptz not null default now();

create unique index if not exists teams_provider_external_id_unique
  on public.teams (provider, external_id)
  where provider is not null and external_id is not null;

alter table public.players
  add column if not exists external_id text,
  add column if not exists provider text,
  add column if not exists image_url text,
  add column if not exists season text,
  add column if not exists updated_at timestamptz not null default now();

create unique index if not exists players_provider_external_id_unique
  on public.players (provider, external_id)
  where provider is not null and external_id is not null;

create table if not exists public.data_sources (
  id bigint generated by default as identity primary key,
  provider text not null,
  sport text not null default 'Football',
  competition text not null,
  season text not null,
  provider_league_id text,
  provider_season_id text,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider, competition, season)
);

alter table public.data_sources enable row level security;

drop policy if exists "Public read data sources" on public.data_sources;
create policy "Public read data sources"
  on public.data_sources for select
  using (true);
