create table if not exists public.official_sources (
  id bigint generated by default as identity primary key,
  slug text not null,
  name text not null,
  sport text not null,
  country text,
  region text,
  competition text,
  season text,
  source_url text not null,
  source_type text not null default 'official_site',
  ingestion_method text not null default 'manual_review',
  parser_key text,
  rights_status text not null default 'needs_review',
  priority int not null default 50,
  status text not null default 'watchlist',
  last_checked_at timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (slug, season)
);

create table if not exists public.official_import_runs (
  id bigint generated by default as identity primary key,
  source_slug text not null,
  provider text not null default 'QueensArena Official',
  sport text not null,
  competition text,
  season text,
  source_url text,
  input_file text,
  status text not null default 'completed',
  imported_matches int not null default 0,
  imported_teams int not null default 0,
  imported_players int not null default 0,
  warning_count int not null default 0,
  error_message text,
  created_at timestamptz not null default now()
);

alter table public.official_sources
  add column if not exists source_type text not null default 'official_site',
  add column if not exists ingestion_method text not null default 'manual_review',
  add column if not exists parser_key text,
  add column if not exists rights_status text not null default 'needs_review',
  add column if not exists priority int not null default 50,
  add column if not exists status text not null default 'watchlist',
  add column if not exists last_checked_at timestamptz,
  add column if not exists notes text,
  add column if not exists updated_at timestamptz not null default now();

alter table public.official_sources enable row level security;
alter table public.official_import_runs enable row level security;

drop policy if exists "Public read official sources" on public.official_sources;
create policy "Public read official sources"
  on public.official_sources for select
  using (true);

drop policy if exists "Public read official import runs" on public.official_import_runs;
create policy "Public read official import runs"
  on public.official_import_runs for select
  using (true);
