create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  endpoint text not null unique,
  subscription jsonb not null,
  user_id uuid references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.push_subscriptions enable row level security;

create policy "Public insert push subscriptions"
  on public.push_subscriptions for insert
  with check (true);

create policy "Public update push subscriptions"
  on public.push_subscriptions for update
  using (true)
  with check (true);

create policy "Users read own push subscriptions"
  on public.push_subscriptions for select
  using (auth.uid() = user_id);
