alter table public.leagues
  add column if not exists external_id text,
  add column if not exists provider text,
  add column if not exists season text,
  add column if not exists region text,
  add column if not exists country text,
  add column if not exists gender text not null default 'women',
  add column if not exists data_status text not null default 'verified',
  add column if not exists source_url text,
  add column if not exists updated_at timestamptz not null default now();

alter table public.teams
  add column if not exists external_id text,
  add column if not exists provider text,
  add column if not exists country text,
  add column if not exists region text,
  add column if not exists logo_url text,
  add column if not exists gender text not null default 'women',
  add column if not exists data_status text not null default 'verified',
  add column if not exists source_url text,
  add column if not exists updated_at timestamptz not null default now();

alter table public.players
  add column if not exists external_id text,
  add column if not exists provider text,
  add column if not exists image_url text,
  add column if not exists season text,
  add column if not exists gender text not null default 'women',
  add column if not exists data_status text not null default 'verified',
  add column if not exists source_url text,
  add column if not exists updated_at timestamptz not null default now();

alter table public.matches
  add column if not exists season text,
  add column if not exists gender text not null default 'women',
  add column if not exists data_status text not null default 'verified',
  add column if not exists source_url text,
  add column if not exists updated_at timestamptz not null default now();

create unique index if not exists leagues_provider_external_id_unique
  on public.leagues (provider, external_id)
  where provider is not null and external_id is not null;

create unique index if not exists teams_provider_external_id_unique
  on public.teams (provider, external_id)
  where provider is not null and external_id is not null;

create unique index if not exists players_provider_external_id_unique
  on public.players (provider, external_id)
  where provider is not null and external_id is not null;

create table if not exists public.data_sources (
  id bigint generated by default as identity primary key,
  provider text not null,
  sport text not null default 'Football',
  competition text not null,
  season text not null,
  country text,
  region text,
  source_url text,
  provider_league_id text,
  provider_season_id text,
  coverage_level text not null default 'manual',
  reliability text not null default 'official',
  enabled boolean not null default true,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider, competition, season)
);

alter table public.data_sources
  add column if not exists country text,
  add column if not exists region text,
  add column if not exists source_url text,
  add column if not exists coverage_level text not null default 'manual',
  add column if not exists reliability text not null default 'official',
  add column if not exists notes text;

create table if not exists public.data_import_batches (
  id bigint generated by default as identity primary key,
  provider text not null,
  sport text not null,
  competition text,
  season text,
  source_url text,
  status text not null default 'completed',
  imported_count int not null default 0,
  warning_count int not null default 0,
  error_message text,
  created_at timestamptz not null default now()
);

create table if not exists public.data_corrections (
  id bigint generated by default as identity primary key,
  entity_type text not null,
  entity_id text not null,
  field_name text not null,
  previous_value text,
  corrected_value text not null,
  source_url text,
  note text,
  created_at timestamptz not null default now()
);

alter table public.data_sources enable row level security;
alter table public.data_import_batches enable row level security;
alter table public.data_corrections enable row level security;

drop policy if exists "Public read data sources" on public.data_sources;
create policy "Public read data sources"
  on public.data_sources for select
  using (true);

drop policy if exists "Public read data import batches" on public.data_import_batches;
create policy "Public read data import batches"
  on public.data_import_batches for select
  using (true);

drop policy if exists "Public read data corrections" on public.data_corrections;
create policy "Public read data corrections"
  on public.data_corrections for select
  using (true);
