create table if not exists public.leagues (
  id bigint generated by default as identity primary key,
  name text not null,
  sport text not null default 'Football',
  region text,
  country text,
  created_at timestamptz not null default now()
);

create unique index if not exists leagues_name_unique
  on public.leagues (name);

create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  name text not null,
  sport text not null default 'Football',
  country text,
  logo_url text,
  created_at timestamptz not null default now()
);

create unique index if not exists teams_name_unique
  on public.teams (name);

create table if not exists public.players (
  id bigint generated by default as identity primary key,
  team_id bigint references public.teams(id) on delete set null,
  name text not null,
  sport text not null default 'Football',
  position text,
  nationality text,
  age int,
  goals int not null default 0,
  assists int not null default 0,
  appearances int not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.roster_memberships (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.players(id) on delete cascade,
  team_id bigint not null references public.teams(id) on delete cascade,
  season text not null,
  competition text,
  shirt_number int,
  role text,
  active boolean not null default true,
  provider text,
  external_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (player_id, team_id, season, competition)
);

create table if not exists public.player_season_stats (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.players(id) on delete cascade,
  team_id bigint references public.teams(id) on delete set null,
  season text not null,
  competition text,
  sport text not null default 'Football',
  appearances int not null default 0,
  starts int not null default 0,
  minutes int not null default 0,
  goals int not null default 0,
  assists int not null default 0,
  yellow_cards int not null default 0,
  red_cards int not null default 0,
  saves int not null default 0,
  source text,
  updated_at timestamptz not null default now(),
  unique (player_id, team_id, season, competition)
);

create table if not exists public.team_season_stats (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.teams(id) on delete cascade,
  season text not null,
  competition text,
  sport text not null default 'Football',
  played int not null default 0,
  won int not null default 0,
  draw int not null default 0,
  lost int not null default 0,
  goals_for int not null default 0,
  goals_against int not null default 0,
  points int not null default 0,
  source text,
  updated_at timestamptz not null default now(),
  unique (team_id, season, competition)
);

create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  external_id text unique,
  sport text not null default 'Football',
  home_team text not null,
  away_team text not null,
  home_score int not null default 0,
  away_score int not null default 0,
  venue text,
  status text not null default 'SCHEDULED',
  starts_at timestamptz,
  competition text,
  source text,
  region text,
  created_at timestamptz not null default now()
);

create table if not exists public.standings (
  id bigint generated by default as identity primary key,
  league text not null,
  team text not null,
  played int not null default 0,
  won int not null default 0,
  draw int not null default 0,
  lost int not null default 0,
  goals_for int not null default 0,
  goals_against int not null default 0,
  points int not null default 0,
  position int not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  title text not null,
  message text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  team_id bigint not null references public.teams(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, team_id)
);

create table if not exists public.sync_queue (
  id bigint generated by default as identity primary key,
  type text not null,
  payload jsonb not null,
  status text not null default 'PENDING',
  attempts int not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.sync_logs (
  id bigint generated by default as identity primary key,
  status text not null,
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.leagues enable row level security;
alter table public.teams enable row level security;
alter table public.players enable row level security;
alter table public.roster_memberships enable row level security;
alter table public.player_season_stats enable row level security;
alter table public.team_season_stats enable row level security;
alter table public.matches enable row level security;
alter table public.standings enable row level security;
alter table public.notifications enable row level security;
alter table public.favorites enable row level security;
alter table public.sync_queue enable row level security;
alter table public.sync_logs enable row level security;

create policy "Public read leagues"
  on public.leagues for select
  using (true);

create policy "Public read teams"
  on public.teams for select
  using (true);

create policy "Public read players"
  on public.players for select
  using (true);

create policy "Public read roster memberships"
  on public.roster_memberships for select
  using (true);

create policy "Public read player season stats"
  on public.player_season_stats for select
  using (true);

create policy "Public read team season stats"
  on public.team_season_stats for select
  using (true);

create policy "Public read matches"
  on public.matches for select
  using (true);

create policy "Public read standings"
  on public.standings for select
  using (true);

create policy "Public read notifications"
  on public.notifications for select
  using (true);

create policy "Users read own favorites"
  on public.favorites for select
  using (auth.uid() = user_id);

create policy "Users insert own favorites"
  on public.favorites for insert
  with check (auth.uid() = user_id);

create policy "Users delete own favorites"
  on public.favorites for delete
  using (auth.uid() = user_id);
