create table if not exists public.roster_memberships (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.players(id) on delete cascade,
  team_id bigint not null references public.teams(id) on delete cascade,
  season text not null,
  competition text,
  shirt_number int,
  role text,
  active boolean not null default true,
  provider text,
  external_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (player_id, team_id, season, competition)
);

create table if not exists public.player_season_stats (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.players(id) on delete cascade,
  team_id bigint references public.teams(id) on delete set null,
  season text not null,
  competition text,
  sport text not null default 'Football',
  appearances int not null default 0,
  starts int not null default 0,
  minutes int not null default 0,
  goals int not null default 0,
  assists int not null default 0,
  yellow_cards int not null default 0,
  red_cards int not null default 0,
  saves int not null default 0,
  source text,
  updated_at timestamptz not null default now(),
  unique (player_id, team_id, season, competition)
);

create table if not exists public.team_season_stats (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.teams(id) on delete cascade,
  season text not null,
  competition text,
  sport text not null default 'Football',
  played int not null default 0,
  won int not null default 0,
  draw int not null default 0,
  lost int not null default 0,
  goals_for int not null default 0,
  goals_against int not null default 0,
  points int not null default 0,
  source text,
  updated_at timestamptz not null default now(),
  unique (team_id, season, competition)
);

alter table public.roster_memberships enable row level security;
alter table public.player_season_stats enable row level security;
alter table public.team_season_stats enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'roster_memberships'
      and policyname = 'Public read roster memberships'
  ) then
    create policy "Public read roster memberships"
      on public.roster_memberships for select
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'player_season_stats'
      and policyname = 'Public read player season stats'
  ) then
    create policy "Public read player season stats"
      on public.player_season_stats for select
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'team_season_stats'
      and policyname = 'Public read team season stats'
  ) then
    create policy "Public read team season stats"
      on public.team_season_stats for select
      using (true);
  end if;
end $$;
