create table if not exists public.sports_poll_responses (
  id bigint generated by default as identity primary key,
  selected_sports text[] not null default '{}',
  other_sport text,
  email text,
  locale text,
  user_agent text,
  created_at timestamptz not null default now()
);

alter table public.sports_poll_responses enable row level security;

drop policy if exists "sports_poll_responses_admin_only" on public.sports_poll_responses;

create policy "sports_poll_responses_admin_only"
  on public.sports_poll_responses
  for all
  using (false)
  with check (false);

create index if not exists sports_poll_responses_created_at_idx
  on public.sports_poll_responses (created_at desc);
